### ISSUE TITLE
AWS ECR Support in the Registry Component

### ISSUE THREAD

**Issue by sshookman** [carsdotcom/skelebot#128]
### Context
Currently the registry component does not support publishing the project docker image to AWS ECR with the `~/.aws` credentials.

### Feature
Add the ability for the registry component to publish the project docker image to AWS ECR by allow the user to specify aws details in the configuration.

```
registry:
    host: 12345.us-east-1.amazonaws.com
    aws
        region: us-east-1
        profile: dev
```

---

### Acceptance Criteria
- [x] Registry component config updated to accept optional `aws` object
- [x] In the Registry config: aws.region is required, aws.profile is optional
- [x] Return a nice error message if the user does not have the 'aws' cli installed
- [x] Add new unit tests for authenticating with AWS ECR and publishing images to ECR
- [x] Update the GitHub Pages Docs
- [x] Update the Changelog
- [x] Bump the Minor Version Number
